### ISSUE TITLE
Failed to use module for terraform >= 1.3.0

### ISSUE THREAD

**Issue by Thibaut-Padok** [padok-team/terraform-azurerm-keyvault#16]
## Error: ##
<img width="1117" alt="error" src="https://user-images.githubusercontent.com/114929258/203570859-4e8d4f17-87f8-44ed-92f8-b3245c88fa1e.png">

## To reproduce: ##
* Backend config _settings.tf:
<img width="363" alt="to-reproduce-backend" src="https://user-images.githubusercontent.com/114929258/203570835-4507f362-1da0-403e-8f6d-921094319406.png">
* Module usage:
<img width="462" alt="to-reproduce-module-call" src="https://user-images.githubusercontent.com/114929258/203570840-f7a60ba3-1c18-4363-97c5-9d83b8b6e544.png">

**Comment by piaverous** [comment]
Resolved in https://github.com/padok-team/terraform-azurerm-keyvault/releases/tag/v0.5.0
